module.exports = {
subradicalInfo: {
    // Level 1
    barb: [],
    big: [],
    construction: [],
    cross: [],
    drop: [],
    enter: [],
    fins: [],
    ground: [],
    gun: [],
    leaf: [],
    lid: [],
    mountain: [],
    mouth: [],
    nine: [],
    person: [],
    power: [],
    prison: [],
    river: [],
    seven: [],
    slide: [],
    stick: [],
    sun: [],
    toe: [],
    tree: [],
    two: [],
    woman: [],
    
    // Level 2
    "book": ["tree", "ground"],
    "bow": [],
    "child": ["barb", "ground"],
    "cow": ["cross", "gun"],
    "dirt": ["cross", "ground"],
    "dog": ["big", "drop"],
    "evening": ["prison", "drop"],
    "eye": [],
    "fire": ["person"],
    "five": ["ground"],
    "flag": [],
    "hair": [],
    "hand": ["barb", "slide"],
    "head": [],
    "heaven": ["two", "person", "big", "ground"],
    "king": [],
    "legs": [],
    "middle": ["mouth", "stick"],
    "moon": ["sun"],
    "narwhal": ["slide", "ground"],
    "private": [],
    "rice-paddy": ["mouth", "cross"],
    "small": ["barb", "fins"],
    "stand": ["ground", "lid"],
    "stone": ["leaf", "mouth"],
    "stool": [],
    "stop": ["toe", "ground"],
    "street": ["barb", "ground"],
    "sword": [],
    "thousand": ["slide", "cross"],
    "treasure": ["slide"],
    "water": ["barb"],
    "white": ["sun", "drop"],
    "writing": ["lid"],

    // Level 3
    "arrow": ["big", "gun"],
    "canopy": ["lid"],
    "direction": ["lid"],
    "door": ["ground", "flag"],
    "dry": ["two", "stick", "cross"],
    "father": ["fins", "treasure"],
    "fingers": [],
    "fur": ["hair"],
    "hat": [],
    "heart": ["cow", "ground", "slide"],
    "life": ["hat"],
    "now": [],
    "old": ["cross", "mouth"],
    "origin": ["two", "legs"],
    "poop": ["private"],
    "spoon": [],
    "task": ["head"],
    "towel": ["head", "stick"],
    "triceratops": [],
    "winter": [],
    
    // Level 4
    "alligator": ["umbrella"],
    "bamboo": ["barb", "gun"],
    "bed": [],
    "beggar": ["gun", "prison"],
    "branch": ["cross", "stool"],
    "car": ["sun"],
    "ceremony": ["drop"],
    "cliff": [],
    "ear": [],
    "energy": ["gun"],
    "flowers": ["ground"],
    "foot": ["mouth"],
    "forehead": [],
    "horns": [],
    "insect": ["private", "mouth"],
    "leader": [],
    "loiter": ["leader"],
    "master": ["drop", "king"],
    "measurement": ["drop", "barb", "ground"],
    "not": [],
    "pi": ["legs", "ground"],
    "plate": [],
    "red": ["legs", "fins", "dirt"],
    "rice": ["tree", "horns"],
    "roof": [],
    "samurai": [],
    "see": ["eye", "legs"],
    "shellfish": ["eye", "fins"],
    "spikes": ["ground"],
    "spirit": [],
    "thread": ["poop", "small"],
    "umbrella": [],
    "world": ["ground", "lion", "box"],

    // Level 5
    "axe": [],
    "blue": ["life", "moon"],
    "coffin": ["ground", "slide"],
    "color": ["bed", "prison"],
    "feathers": ["cape", "ice"],
    "go": ["loiter", "two", "street"],
    "gold": ["hat", "king", "horns"],
    "ice": ["drop"],
    "key": ["gun"],
    "kick": [],
    "lantern": ["twenty"],
    "lip-ring": ["mouth"],
    "meat": ["person", "head"],
    "meet": ["hat", "cloud", "private", "two"],
    "mustache": ["mouth", "head"],
    "rain": ["head"],
    "run": ["dirt", "coat-rack"],
    "say": ["mouth"],
    "scooter": [],
    "self": [],
    "tsunami": ["drop"],
    "twenty": ["cross"],
    "viking": ["roof", "horns"],
    "village": ["rice-paddy", "dirt"],
    "west": ["pi", "mouth"],
    "window": ["cross"],
    "wolverine": [],

    // Level 5

    // Level 11 - 20


    // Level 41 - 50
    cactus: [],
    signpost: ["winter"],
    bone: ["mustache", "forehead", "moon"],
    melon: [],
    satellite: [],
    shop: ["flag", "ground", "private", "dirt"],
    badger: [],
    imperial: ["moon", "stand"],
    plow: ["slide", "dirt", "tree"],
    can: ["mountain", "gun"],
    dragon: ["stand", "rice-paddy", "umbrella"],
    wind: ["table", "slide", "insect"],
    again: ["ground", "rice-paddy", "treasure"],
    house: ["roof", "pig"],
    protect: ["roof", "measurement"],
    fat: ["big", "drop"],
    favor: ["cross", "rice-paddy", "heart"],
    penguin: ["fins", "towel", "winter"],
    wave: ["tsunami", "skin"],
    form: ["roof", "valley"],
    mysterious: ["lid", "poop"],
    sunlight: ["triceratops", "pi"],
    "crab-trap": ["cage", "legs", "crab"],
    times: ["mouth"],
    name: ["evening", "mouth"],
    psychopath: ["forehead", "hair", "spoon", "box", "treasure"],
    splinter: ["turtle-shell", "mustache", "head"],

    // Level 51 - 60
    stomach: ["rice-paddy", "moon"],
    frostbite: ["dirt", "legs", "winter"],
    tall: ["lid", "mouth", "mustache"],
    doubt: ["spoon", "mama", "arrow", "coat-rack"],
    concave: [],
    convex: [],
    below: ["ground", "toe"],
    courage: ["mama", "man"]
}};

