module.exports = {
subradicalInfo: {
    // Level 1 - 10
    barb: [],
    big: [],
    construction: [],
    cross: [],
    drop: [],
    enter: [],
    fins: [],
    ground: [],
    gun: [],
    leaf: [],
    lid: [],
    mountain: [],
    mouth: [],
    nine: [],
    person: [],
    power: [],
    prison: [],
    river: [],
    seven: [],
    slide: [],
    stick: [],
    sun: [],
    toe: [],
    tree: [],
    two: [],
    woman: [],
    
    // Level 11 - 20
    

    // Level 41 - 50
    cactus: [],
    signpost: ["winter"],
    bone: ["mustache", "forehead", "moon"],
    melon: [],
    satellite: [],
    shop: ["flag", "ground", "private", "dirt"],
    badger: [],
    imperial: ["moon", "stand"],
    plow: ["slide", "dirt", "tree"],
    can: ["mountain", "gun"],
    dragon: ["stand", "rice-paddy", "umbrella"],
    wind: ["table", "slide", "insect"],
    again: ["ground", "rice-paddy", "treasure"],
    house: ["roof", "pig"],
    protect: ["roof", "measurement"],
    fat: ["big", "drop"],
    favor: ["cross", "rice-paddy", "heart"],
    penguin: ["fins", "towel", "winter"],
    wave: ["tsunami", "skin"],
    form: ["roof", "valley"],
    mysterious: ["lid", "poop"],
    sunlight: ["triceratops", "pi"],
    "crab-trap": ["cage", "legs", "crab"],
    times: ["mouth"],
    name: ["evening", "mouth"],
    psychopath: ["forehead", "hair", "spoon", "box", "treasure"],
    splinter: ["turtle-shell", "mustache", "head"],

    // Level 51 - 60
    stomach: ["rice-paddy", "moon"],
    frostbite: ["dirt", "legs", "winter"],
    tall: ["lid", "mouth", "mustache"],
    doubt: ["spoon", "mama", "arrow", "coat-rack"],
    concave: [],
    convex: [],
    below: ["ground", "toe"],
    courage: ["mama", "man"]
}};

