module.exports = {
subradicalInfo: {
    // Level 1
    barb: [],
    big: [],
    construction: [],
    cross: [],
    drop: [],
    enter: [],
    fins: [],
    ground: [],
    gun: [],
    leaf: [],
    lid: [],
    mountain: [],
    mouth: [],
    nine: [],
    person: [],
    power: [],
    prison: [],
    river: [],
    seven: [],
    slide: [],
    stick: [],
    sun: [],
    toe: [],
    tree: [],
    two: [],
    woman: [],
    
    // Level 2
    "book": ["tree", "ground"],
    "bow": [],
    "child": ["barb", "ground"],
    "cow": ["cross", "gun"],
    "dirt": ["cross", "ground"],
    "dog": ["big", "drop"],
    "evening": ["prison", "drop"],
    "eye": [],
    "fire": ["person"],
    "five": ["ground"],
    "flag": [],
    "hair": [],
    "hand": ["barb", "slide"],
    "head": [],
    "heaven": ["two", "person", "big", "ground"],
    "king": [],
    "legs": [],
    "middle": ["mouth", "stick"],
    "moon": ["sun"],
    "narwhal": ["slide", "ground"],
    "private": [],
    "rice-paddy": ["mouth", "cross"],
    "small": ["barb", "fins"],
    "stand": ["ground", "lid"],
    "stone": ["leaf", "mouth"],
    "stool": [],
    "stop": ["toe", "ground"],
    "street": ["barb", "ground"],
    "sword": [],
    "thousand": ["slide", "cross"],
    "treasure": ["slide"],
    "water": ["barb"],
    "white": ["sun", "drop"],
    "writing": ["lid"],
    
    // Level 11 - 20
    

    // Level 41 - 50
    cactus: [],
    signpost: ["winter"],
    bone: ["mustache", "forehead", "moon"],
    melon: [],
    satellite: [],
    shop: ["flag", "ground", "private", "dirt"],
    badger: [],
    imperial: ["moon", "stand"],
    plow: ["slide", "dirt", "tree"],
    can: ["mountain", "gun"],
    dragon: ["stand", "rice-paddy", "umbrella"],
    wind: ["table", "slide", "insect"],
    again: ["ground", "rice-paddy", "treasure"],
    house: ["roof", "pig"],
    protect: ["roof", "measurement"],
    fat: ["big", "drop"],
    favor: ["cross", "rice-paddy", "heart"],
    penguin: ["fins", "towel", "winter"],
    wave: ["tsunami", "skin"],
    form: ["roof", "valley"],
    mysterious: ["lid", "poop"],
    sunlight: ["triceratops", "pi"],
    "crab-trap": ["cage", "legs", "crab"],
    times: ["mouth"],
    name: ["evening", "mouth"],
    psychopath: ["forehead", "hair", "spoon", "box", "treasure"],
    splinter: ["turtle-shell", "mustache", "head"],

    // Level 51 - 60
    stomach: ["rice-paddy", "moon"],
    frostbite: ["dirt", "legs", "winter"],
    tall: ["lid", "mouth", "mustache"],
    doubt: ["spoon", "mama", "arrow", "coat-rack"],
    concave: [],
    convex: [],
    below: ["ground", "toe"],
    courage: ["mama", "man"]
}};

